esphome:
  name: bedroom-light

esp8266:
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: "WPA2"

  ap:
    ssid: "Bedroom-Light Fallback Hotspot"
    password: !secret ap_fallback_password

logger:

ota:
  - platform: esphome
    password: !secret ota_password
    
web_server:
  port: 80
  version: 3
