esphome:
  name: bedroom-light
  friendly_name: 'Bedroom Light'
  on_boot:
    priority: -10
    then:
      - switch.turn_on: light_power
      - script.execute: reset_to_base
      - script.execute: set_highest_brightness

esp8266:
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: 'WPA2'
  fast_connect: true
  ap:
    ssid: 'Bedroom Light Fallback Hotspot'
    password: !secret ap_fallback_password

api:
  encryption:
    key: !secret api_encryption_key

logger:

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: sntp
    id: home_time
    timezone: !secret timezone

web_server:
  port: 80
  version: 3

remote_transmitter:
  id: ir_transmitter
  pin: 14
  carrier_duty_percent: 50%

binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    name: 'Physical Button'
    on_press:
      then:
        - switch.toggle: light_power

select:
  - platform: template
    name: 'Light Temperature Mode'
    id: light_temperature_select
    options:
      - 'Daylight'
      - 'Warm'
    optimistic: true
    initial_option: 'Warm'
    set_action:
      - script.execute: transmit_temperature_toggle

switch:
  - platform: template
    name: 'Power'
    id: light_power
    optimistic: true
    turn_on_action:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x9C
    turn_off_action:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0xDD

button:
  - platform: template
    name: Increase brightness
    icon: mdi:arrow-up-circle
    id: increase_decrease
    on_press:
      - script.execute:
          id: transmit_brightness_increase

  - platform: template
    name: Decrease brightness
    icon: mdi:arrow-down-circle
    id: brightness_decrease
    on_press:
      - script.execute:
          id: transmit_brightness_decrease

  - platform: template
    name: Reset to base
    id: button_reset_to_base
    on_press:
      - script.execute:
          id: reset_to_base

  - platform: template
    name: Set highest brightness
    id: button_set_highest_brightness
    on_press:
      - script.execute:
          id: set_highest_brightness

script:
  - id: reset_to_base
    then:
      - script.execute:
          id: set_lowest_brightness
      # After a color change, a temperature toggle always sets to warm.
      - script.execute:
          id: transmit_red_toggle
      - select.set:
          id: light_temperature_select
          option: 'Warm'

  - id: set_lowest_brightness
    then:
      - repeat:
          count: 4
          then:
            - script.execute:
                id: transmit_brightness_decrease

  - id: set_highest_brightness
    then:
      - repeat:
          count: 4
          then:
            - script.execute:
                id: transmit_brightness_increase

  - id: transmit_brightness_decrease
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x80

  - id: transmit_brightness_increase
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x82

  - id: transmit_red_toggle
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x01

  - id: transmit_temperature_toggle
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x86

  - id: transmit_flipper_nec
    mode: restart
    parameters:
      address: int
      command: int
    then:
      - remote_transmitter.transmit_nec:
          # 1. Take the input byte (e.g., 0x80)
          # 2. Calculate the inverse (~0x80 = 0x7F)
          # 3. Shift inverse to the upper byte (0x7F00)
          # 4. Combine them (0x7F00 | 0x80 = 0x7F80)
          address: !lambda 'return ((~address & 0xFF) << 8) | (address & 0xFF);'
          command: !lambda 'return ((~command & 0xFF) << 8) | (command & 0xFF);'
      - delay: 25ms
