esphome:
  name: room-light
  friendly_name: 'Room Light'
  includes:
    - light_schedule.h
  on_boot:
    priority: -10
    then:
      - wait_until:
          condition:
            lambda: 'return id(home_time).now().is_valid();'
      - script.execute: full_reset_and_sync

esp8266:
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: 'WPA2'
  fast_connect: true
  reboot_timeout: 0s
  ap:
    ssid: 'Room Light Fallback Hotspot'
    password: !secret ap_fallback_password

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

logger:

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: sntp
    id: home_time
    timezone: !secret timezone
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          - if:
              condition:
                lambda: |-
                  auto time = id(home_time).now();
                  return is_schedule_breakpoint(time.hour, time.minute);
              then:
                - script.execute: apply_schedule_logic

web_server:
  port: 80
  version: 3

remote_transmitter:
  id: ir_transmitter
  pin: 14
  carrier_duty_percent: 50%

sensor:
  - platform: adc
    pin: A0
    name: 'Brightness Voltage'
    id: brightness_voltage
    unit_of_measurement: V
    accuracy_decimals: 4
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          window_size: 3

binary_sensor:
  - platform: gpio
    pin:
      number: 12
      mode: INPUT_PULLUP
      inverted: true
    name: 'Physical Button State'
    on_press:
      then:
        - switch.toggle: light_power

select:
  - platform: template
    name: 'Light Temperature Mode'
    id: light_temperature_select
    options:
      - 'Daylight'
      - 'Warm'
    optimistic: true
    initial_option: 'Warm'
    set_action:
      - script.execute: transmit_temperature_toggle

number:
  - platform: template
    name: "Brightness Level"
    id: brightness_level
    min_value: 0
    max_value: 4
    step: 1
    initial_value: 0
    optimistic: false
    set_action:
      then:
        - lambda: |-
            int diff = x - id(brightness_level).state;
            if (diff > 0) {
                id(repeat_increase).execute(diff);
            } else if (diff < 0) {
                id(repeat_decrease).execute(abs(diff));
            }
            id(brightness_level).publish_state(x);

switch:
  - platform: template
    name: 'Power'
    id: light_power
    optimistic: true
    turn_on_action:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x9C
    turn_off_action:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0xDD

button:
  - platform: template
    name: 'Reset to Base'
    id: button_reset_to_base
    on_press:
      - script.execute:
          id: reset_to_base

  - platform: template
    name: 'Sync to Schedule'
    on_press:
      - script.execute: full_reset_and_sync

script:
  - id: apply_schedule_logic
    then:
      - lambda: |-
          auto time = id(home_time).now();
          LightState target = get_target_state(time.hour, time.minute);

          if (target.power != id(light_power).state) {
              if (target.power) {
                  id(light_power).turn_on();
              } else {
                  id(light_power).turn_off();
                  return; 
              }
          }

          if (!target.power) {
              return;
          }

          bool current_is_daylight = (std::string(id(light_temperature_select).current_option()) == "Daylight");

          if (target.is_daylight != current_is_daylight) {
              auto call = id(light_temperature_select).make_call();
              call.set_option(target.is_daylight ? "Daylight" : "Warm");
              call.perform();
          }

          auto num_call = id(brightness_level).make_call();
          num_call.set_value(target.level);
          num_call.perform();

  - id: repeat_increase
    mode: queued
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - script.execute: transmit_brightness_increase

  - id: repeat_decrease
    mode: queued
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - script.execute: transmit_brightness_decrease

  - id: full_reset_and_sync
    then:
      - switch.turn_on: light_power
      - script.execute: reset_to_base
      - script.execute: apply_schedule_logic

  - id: reset_to_base
    then:
      - script.execute: set_lowest_brightness
      - script.execute: transmit_red_toggle
      - select.set:
          id: light_temperature_select
          option: 'Warm'
      - lambda: 'id(brightness_level).publish_state(0);'

  - id: set_lowest_brightness
    then:
      - repeat:
          count: 4
          then:
            - script.execute:
                id: transmit_brightness_decrease

  - id: set_highest_brightness
    then:
      - repeat:
          count: 4
          then:
            - script.execute:
                id: transmit_brightness_increase

  - id: transmit_brightness_decrease
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x80

  - id: transmit_brightness_increase
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x82

  - id: transmit_red_toggle
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x01

  - id: transmit_temperature_toggle
    then:
      - script.execute:
          id: transmit_flipper_nec
          address: 0x80
          command: 0x86

  - id: transmit_flipper_nec
    mode: restart
    parameters:
      address: int
      command: int
    then:
      - remote_transmitter.transmit_nec:
          # 1. Take the input byte (e.g., 0x80)
          # 2. Calculate the inverse (~0x80 = 0x7F)
          # 3. Shift inverse to the upper byte (0x7F00)
          # 4. Combine them (0x7F00 | 0x80 = 0x7F80)
          address: !lambda 'return ((~address & 0xFF) << 8) | (address & 0xFF);'
          command: !lambda 'return ((~command & 0xFF) << 8) | (command & 0xFF);'
      - delay: 25ms
